In [5]:
from qdrant_client import QdrantClient
from qdrant_client.models import (
    PointStruct,
    VectorParams,
 
    Distance,
    
)
import pandas as pd
import openai
from langchain_openai import OpenAI
from langchain_anthropic import ChatAnthropic

from langchain_openai import OpenAIEmbeddings

In [6]:
import os

api_key = os.getenv("OPENAI_API_KEY")
if not api_key:
    api_key = input("Please enter your open ai api key").strip()
    os.environ["OPENAI_API_KEY"] = api_key
    if not api_key:
        raise EnvironmentError("No API Key provided")

In [8]:
qdrant_client = QdrantClient(
    url="https://c006961b-c63f-469e-b947-33bbfe692e0c.us-east-1-0.aws.cloud.qdrant.io:6333", 
    api_key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.ruiaT3htpQn4YQY9GTp_UctLaa458w6INYXnVM91JfI",
)

print(qdrant_client.get_collections())

collections=[CollectionDescription(name='Amazon-items-collection-02'), CollectionDescription(name='Amazon-items-collection-01')]

In [48]:
qdrant_client.create_collection(
    "Amazon-items-collection-02",
    vectors_config=VectorParams(
        size=1536, distance=Distance.COSINE)
)

print(qdrant_client.get_collections())

collections=[CollectionDescription(name='Amazon-items-collection-02'), CollectionDescription(name='Amazon-items-collection-01')]

## Read the sample data from inventory metadata

In [11]:
df_items = pd.read_json("../data/meta_Electronics_2022_2023_with_category_ratings_100_sample_1000.jsonl", lines=True)
print(df_items.shape)
df_items.head(2)

(2519, 16)

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Camera & Photo,Rraycom 4Pack Security Cameras Outdoor Wireles...,4.1,456,"[100% wireless design-Fast, wireless setup.Rra...",[],149.97,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': '2K Battery Security Camera BW4', '...",Rraycom,"[Electronics, Camera & Photo, Video Surveillan...",{'Package Dimensions': '12.4 x 8.35 x 3.58 inc...,B0C1NRQ9DQ,NaN,NaN,NaN
1,Camera & Photo,High Power Stars Telescope Monocular - Handhel...,4.0,213,[【HD MAGNIFICATION】 10X magnification and 60mm...,"[SVNRY, Monocular Telescope is, Light Weight, ...",19.50,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'The SVNRY Monocular Telescope', 'u...",Svnry,"[Electronics, Camera & Photo, Binoculars & Sco...",{'Package Dimensions': '7.68 x 3.9 x 3.58 inch...,B0BNMRNVWL,NaN,NaN,NaN

## Concatenate the title and description to create a single text field

In [12]:
def preprocess_items(row):
    return f"{row['title']} {' '.join(row['features'])}"

In [13]:
df_items["preprocessed_data"] = df_items.apply(preprocess_items, axis=1)

In [49]:
df_items["preprocessed_data"].shape

df_sample = df_items.sample(n=50, random_state=5)

In [50]:
df_sample.head(2)

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author,preprocessed_data
1412,Cell Phones & Accessories,"iPhone Charger, 3Pack 3FT MFi Certified Lightn...",4.6,113,"[⚡3 Pack 3 FT Charger Cable - In the Package, ...",[],6.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'These are some great charging sync...,Snisre,"[Electronics, Computers & Accessories, Compute...","{'Brand': 'Snisre', 'Connector Type': 'USB, Li...",B0BL74SNX8,NaN,NaN,NaN,"iPhone Charger, 3Pack 3FT MFi Certified Lightn..."
1370,Cell Phones & Accessories,HALLEAST for Galaxy Buds 2 Pro Case 2022/ Gala...,4.6,6491,[【PREMIUM TPU & METAL】Can't wait to unpack and...,[],13.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Nice case for the buds, install sh...",HALLEAST,"[Electronics, Headphones, Earbuds & Accessorie...",{'Package Dimensions': '5.63 x 3.23 x 0.87 inc...,B09JKFM15D,NaN,NaN,NaN,HALLEAST for Galaxy Buds 2 Pro Case 2022/ Gala...

## Sample 50 items

In [51]:
def get_embeddings(text, model = "text-embedding-3-small"):
    embeddings_model = OpenAIEmbeddings(model = "text-embedding-3-small")
    response = embeddings_model.embed_documents([text])

  
    return response[0]

In [52]:
## Embed data

data_to_embed = df_sample['preprocessed_data'].tolist()

pointstructs = []

for i , data in enumerate(data_to_embed):
    embeddings = get_embeddings(data)
    pointstructs.append(
        PointStruct(
            id=i,
            vector=embeddings,
            payload={'text': data},
        )


    )

In [53]:
qdrant_client.upsert(
    collection_name = "Amazon-items-collection-02",
    wait=True,
    points=pointstructs,

)

UpdateResult(operation_id=0, status=<UpdateStatus.COMPLETED: 'completed'>)

In [43]:
def retrieve_data(query):

    query_embedding = get_embeddings(query)
    results = qdrant_client.query_points(
        collection_name="Amazon-items-collection-01",
        query=query_embedding,
        limit=10,
    )
    return results

In [44]:
retrieve_data("What airphones can I get?").points

[ScoredPoint(id=31, version=3, score=0.4405107, payload={'text': 'Wireless Earbud, Bluetooth 5.1 Headphones with HD Mic, 2023 Mini Bluetooth Earbud Deep Bass, 30H IP7 Waterproof Wireless Headphones, Wireless Earphones in Ear with Touch Control, USB-C Fast Charging Fast Auto Pairing Technology and Bluetooth 5.1: Bluetooth headphones adopts the advanced bluetooth 5.1 technology, which provides more stable connection (15m), faster paring and universal compatibility. No distortion and latency to make your music and phone calls worry free. Simply take the wireless earbud out of the charging case and they will automatically connect to your phone (after being paired the first time), you will be in your music world in a couple of seconds. Superior Hi-Fi Stereo Sound Quality: ueua bluetooth earbud offers a truly natural, authentic sound and powerful bass performance with 10mm large size speaker driver, which produces incredible sound quality with deep bass and crystal clear treble; built-in high quality microphones with noise cancellation for you to enjoy crystal-clear hands-free calls and voice assistant in noisy circumstances. IP7 Waterproof and Sport Fit Design: Certificated with IPX7 waterproof rating and nano-coating material, wireless headphones can prevent any penetration from splash and water, ideal for strenuous workouts and all weather conditions. With ergonomic and sport redesign, I07 headphones wireless bluetooth can fit and stay secured in ear canal even with intense movement. Ideal for sweating it out at the gym. Ideal for jogging, running, yoga, sports, gym, cycling etc. Protable Mini Charging Case: The ear buds alone provide up to 6 hours of high-quality sound output on a single charge, and the included charging case provides an additional 5 charges, providing about 30 hours of total playtime. The upgraded USB-C charging port can provide faster and safer charging. Take it to travel with you, you can enjoy long-lasting music all day and every day. LED Digital Display and Smart Touch Control: Features with touch control sensors, I07 noise cancelling headphones allows you to conveniently power on/off, play/pause, skip songs, enable Siri, answer/hang up, adjust volume and access other functions at the touch of a button. With the individual LED display on the case can help check the power of the noise cancelling earbud and charging case at any time.'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=35, version=3, score=0.41726816, payload={'text': 'Cotogni Wireless Bluetooth 5.3 Earbuds, P5 Wireless Earbuds with Charging Case Wireless Bluetooth Earphones 40H Playtime Waterproof Wireless Earbuds for iPhone, Android 🎧【Upgraded Bluetooth 5.3 &High-Quality Wireless Earbuds 】This Cotogni True wireless earbuds high-end earbuds in controlled, quiet, indoor settings. The sound is expansive, deep, and about as good as any high-end options this Bluetooth Earbuds equipped with 6mm dual dynamic drivers achieve balanced, high-quality sound. 🎧[Mini wireless earbuds Waterptoof& Sweatproof ] Cotogni Wirelesse earbuds Earbuds and charging case inner Nano-coating makes it possible to waterproof for 1 meters deep for 30 minutes. Waterproof and sweatproof latest technology can effectively prevent from the damage of the splash by sweat and raindrops 🎧【 Compact Charging Case Up to 20- 40Hrs Playtime】The Wireless Earbuds compact with charging case is easy to take with you when you are out and about, and it provides long battery life.20 hours of playing music when two earbuds are used together with max volume. It has up to 20 hours of playtime when a single earbud is used. (Needing to use the charging case to charge, a fully charged earbud can be used for 6 hours with max volume.) 🎧【Sound Worthed & Widely Compatibility】 Stereo Headphones in Ear Built in Mic Headset Premium Sound,Sound worthiest in the same level of wireless earbuds. The true wireless earbuds are compatible with all Bluetooth enabled devices for iPhone, Samsung, Huawei, Android/iOS smartphones, iPods, iPad, tablets, etc. ensure stable sound and penetrating power, even in a noisy environment can provide clear voice detection. You can enjoy your personal space whether you are indoors, outdoor, work or exercise. 🎧【Smart Touch Control & Clear Call】】 - Cotogni earbuds support convenient touch control, such as pause, play, volume control, prev/next song, answer calls, and voice assistant control. Free your hands from the devices. 🎧【 HD Stereo Musi& Comfortable to Wear】The Bluetooth Headphonesis made of 30° soft rubber. Built-in sensitive touch control key on the ear buds, which let you easily manage music or phone calls. Change songs or adjust volume, or make phone call, all operations at your fingertips without taking out your mobile phone. Compared with physical button, it largely minimizes the pressure to your ears. Wireless Earbuds sports earphones fit perfectly in your ears and stay in place even you are doing strenuous sweaty exercise, never worry about them falling out.Enjoy a cozy experience all day. ⭐⭐ 【One Step Ppairing and Warring NOTE】 Simply take 2 headsets out from the charging case, and they will connect each other automatically and then only one ste 1. Before pairing the earbuds, please kindly remove the insulating film on the earbuds first. 2. Please dry the earbuds before you put them back into the charging case. Please read the [User Manual] carefully before using, any problems please feel free to contact us.g】 Simply take 2 headsets out from the charging case, and they will connect each other automatically and then only one step easily enter mobile phone Bluetooth setting to pair the earbuds.'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=46, version=3, score=0.40614694, payload={'text': 'comiso Cell Phone Stand with Wireless Bluetooth Speaker, Punchy Bass & HD Stereo Sound Speaker for Home & Outdoors Compatible with iPhone/ipad/Samsung, Unique Ideal Gifts for Men Women-Black ♫【 AMAZING STEREO SOUND 】- COMISO Bluetooth Speaker is equipped with a full range 5W drivers, which perfectly realizes enhanced bass, accurate mids and clear highs sound, which great suitable for listening to music & watching movies. ♫【 PREFERRED GIFTS FOR MEN & WOMEN WHO HAVE EVERYTHING 】 - Phone Stand with Wireless Bluetooth Speaker provide you with adjustable viewing angle and louder voice. Idea cool phone gadget gift for your family and friends great for mother\'s day, Father’s day, Christmas, Birthday, Anniversary or any other special holidays. ♫【 BLUETOOTH 5.1 SPEAKER with HOLDER 】 - A new generation of Bluetooth 5.1, has lower power consumption, faster transmission and more stable signal without any delay. This portable wireless speaker is compatible with multiple bluetooth devices. Wireless speaker with microphone makes taking & making calls a breeze. ♫【 FOLDABLE & PORTABLE PHONE STAND 】 - The universal adjustable phone stand speaker can be titled to vertical, It allows you to get a more comfortable viewing angle. Reduce the frequency of looking down at the phone screen to avoid hurting your back and neck. Makes you hands-free to enjoy your games, videos and Facetime. ♫ 【 STABLE and WIDE COMPATIBILITY 】 - This cell phone holder for desk is equipped with a weighted base. Therefore, this phone stand holder with speaker is stable enough to support all 4"-12" smartphones or tablets. Compatible with Apple, iPhone, Samsung phone, Kindel, Switch, iPad Mini, iPad Air, and other 4"-12" tablets etc. And its non-slip rubber pad prevents your device from accidentally slipping. ♫【 TRUE WIRELESS & HD SURROUND SOUND 】 - 360-degree surround sound can easily fill up your room. WHAT YOU GET - X8 Phone Stand with Speaker, USB Type-C charging cable, Instruction manual, 12-month warranty card.'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=6, version=3, score=0.39885575, payload={'text': 'Type USB C to 3.5mm Female Adapter,USB C to Aux Audio Dongle Cable Cord Headphone Jack Compatible with Pixel 4 3 XL,Samsung Galaxy S21 S20 Ultra S20+ Note 20 10S10 S9 Plus,iPad Pro,Mate 30 Pro(Silver) 🎻【HI-FI AUDIO ADAPTER】 : Delivers crystal-clear digital & analog sound at up to 96kHz/24bit. Works with almost any 3.5 mm jack or USB-C port. 🎻【MULTIFUNCTIONAL】 : Listen to music, take phone calls, or adjust the volume with this versatile adapter. 🎻【HI-RES DAC CHIP 】:A high-fidelity DAC chip provides enhanced noise reduction & ensures stable lossless audio transmission. 🎻【Universal Compatibility】: This adapter compatible with the Google Pixel 2/3/4/5 and XL Samsung Note20/Note20 Ultra/Note10/10 Plus/A8/A80/S21/S21 Plus/S21 Ultra/S20/S20 Plus/S20 Ultra/S20 FE/Z Flip HTC 10/U11/U11 Plus/U Ultra Huawei Mate 10/20/30/P20/P30 and Pro OnePlus 9/9 Pro/8/8 Pro/8T/7/7 Pro Motorola moto z3/z3 play Compatible with iPad mini 6 and more 🎻【BUILT TO LAST】: Corrosion-resistant aluminum casing protects the chip, while the braided nylon shielding can withstand up to 10,000 bends with a tensile strength of 20 kg.'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=15, version=3, score=0.3657581, payload={'text': 'JTOMEI AirPods 3 Case Cover with Keychain, Full Protective Silicone Case Accessories for AirPods 3rd Generation, Front LED Visible, Olive Green Compatibility: ONLY designed for Apple AirPods 3rd generation charging case(Released on 2021). NOT for AirPods 1st, 2nd Gen and AirPods Pro. Full Protection: Sturdy soft silicone case, which provides fully protection for your AirPods 3 against drops, scratches and bumps without any bulk. Premium Silicone Material: Made of premium silicone material, soft & smooth surface,more durable. We also have many colors to choose for your AirPods 3. Support Wired & Wireless Charging: Support wired and wireless charging without removing the case.The front LED light remains visible while charging. What You Get: AirPods 3rd generation silicone case x1, metal carabiner clip x1(NOT INCLUDE AIRPODS 3). Any question please feel free to contact us.'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=38, version=3, score=0.36562264, payload={'text': 'Winproo Armor Airpods 2nd & 1st Generation Case Cover with Lock Clip, Military Hard Shell Full-Body Shockproof Protective Case Skin with Keychain for Airpods 2nd & 1st Gen (Yellow) [Compatible with Airpods 2 & 1 Case] Winproo armor series\xa0Airpods 2nd & 1st generation case cover is specially designed for both Apple AirPods 2nd and AirPods 1st generation charging case. PLEASE NOTE: Not compatible with AirPods Pro & 3rd generation case [360-Degree Full-Body Case Protector] Sturdy Airpods 2 & 1 generation case hard shell is made of environmental friendly TPU material and shockproof protective corner design will definitely provide comprehensive protection for your Airpods case against daily drops, bumps and scratches [Convenient Charging] 2 pieces separated design make it easy to install and remove the case cover. Cool Airpods 2nd &1st generation case support both wired and wireless charging without removing the hard case cover. Charging LED light is visible during the charging [Airpods 2nd & 1st Generation Case with Lock Clip] Secure locking lid make sure the Airpods 2 and 1 case cover won’t opened accidently when carrying or dropping. Equipped with a metal carabiner keychain clip to help you conveniently carry your AirPods 2 &1 gen anywhere [Reset Button Access] Reset button on the back of this hard AirPods 2nd & 1st gen case allows you to reset or pair your Airpods 2nd & 1st Generation without taking out the charging case. [What You’ll Get] 1* Case Cover for Airpods 2nd & 1st gen, 1*Metal Carabiner Keychain Clip, 1*Spare Adhesive Tape (AirPods 2nd & 1st gen &Charging Case are NOT included.)'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=0, version=3, score=0.34893388, payload={'text': 'iPhone Charger, 3Pack 3FT MFi Certified Lightning Cable Fast Charging Cord Compatible with iPhone 14 13 12 11 XS XR X Pro Max Mini 8 7 6S 6 Plus 5S SE iPad iPod AirPods… ⚡3 Pack 3 FT Charger Cable - In the Package, you will get 3 pack 3 ft USB-A to Lightning Fast Charging Cord, 3ft charging cable makes convenient to charge your device in bedroom, sofa, office, back seat of car, travel. Keep a cable in your home or office as a backup, avoid the trouble of having only one data cable. ⚡Durable Material - iPhone lightning cable with pure copper core and premium TPE surface greatly improve charging efficency and durability. With 20000+ bend lifespan test in the laboratory environment and superior functionality under heavy daily usage, the iPhone charging cord could provide with a long time service. ⚡High Speed Data Sync & Charge - Certified cable provides a fast, secure and stable charging solution for your Apple devices. It provides a safer charging current, supports maximum transfer rate up to 480Mbs and high-speed charging up to 2.4 A, which enhance the charging efficiency. ⚡Wide Compatible with iPhone Devices - MFi Certified lightniing cable compatible with iPhone 14/13/12/11/XS/XR/X/8 Plus/8/7 Plus/7/6s Plus/ 6s/6 Plus /6/5s/5c 5/iPad Pro/ iPad Air/Air 2/iPad mini/mini 2/mini 4 /iPad 4th gen/iPod Touch 5th gen/iPod nano 7th gen and Beats Pill+. ⚡Thoughtful After-sales Service - If you have any questions with our iphone charger cable, please feel free to contact our after-sales Service. Our service team will provide you with a satisfactory solution within 24 hours.'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=9, version=3, score=0.34799564, payload={'text': 'Airpods 3rd Generation Case Men Lock with Cleaning Kit, GARTOO Protective Cover with Cleaning Pen Compatible with Airpod 3rd Gen Case, Shockproof Rugged Shell for Air Pods 3 2021 Charging Case, Black ✅Upgraded Secure Lock -- The locking function can secure the cover of the shell firmly, open the top cover with one click. The AirPods 3rd gen case also comes with a portable carabiner clip to easily hook it on to your bag, belt loop, keys...at your convenience. ✅Shockproof Airpod 3rd Generation Case -- Compact TPU material with upgraded edge buffer, this cool armor will protect your airpods 3rd gen (2021) from dropping or scratch. Stylish design will transform your AirPod 3. ✅Compatible Device -- Newly Armor Series full-body shockproof Airpods 3rd gen case is specially designed for Apple AirPods 3rd Generation charging case only. ( Please Note:❌Airpods 3 and charging case are not included.) ✅Integrated cleaning pen design -- Pull down one side is chearging hole cleaning brush，The other side Pull down is plush brush&round metal nib; Convenient Double-head hidden design, cleaning pen will meet the cleaning needs of many situations. ✅Package Included -- 1*Cover Case for Airpods 3rd Generation, 1*Carabiner, 1*Spare Adhesive Tape, 1* cleaning kit pen.'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=41, version=3, score=0.3469882, payload={'text': "Maxjoy for Airpods Pro 2nd Generation/1st Generation Case Cover, AirPod Pro 2 Case for Women Men Cute Protective Hard iPod Pro 2 Cover with Keychain for AirPods Pro (2022/2019), Leopard Print 〖Premium Material〗 Protective hard case covers design for AirPods pro 2nd/1st generation are made of high quality premium PC material, the surface polished same visual and feel as bare metal, which can protect your ipod pro 2 charging case from most of the daily drops scratches and bumps without adding any bulk. 〖Gold Frame Design〗 Stylish patterns are protected with PET film,rose golden frame case shell designed for air pod pro for women men. Vivid colors will not fade over time. Fashionable air pods pro 2 case make you unique and standing out always. It's easy and convenient for you to take your air-pod pro 2nd generation case 2022 with carabiner keychain. 〖Unique & Elegant Pattern〗 Stylish unique patterns design for AirPods pro 2 case covers are made with advanced equipment. Multiple colour for choose making your airpod pros 2022 case unique,fashionable and elegant without fading. 〖Support Wired/Wireless Charging〗 Precise cutout offers a free access to the charging port to charger your AirPods pro 2nd gen without removing the protective case, the LED light is visible while wired/wireless charging Simply. It's convenient & compact carrying case design for AirPods pro 2022/2019. No interference to all tap sensor and charging functions. 〖What’s in the Box〗 Package Includes : 1x case for airpod pro 2nd/1st gen, 1 x Keychain (NOT INCLUDE AirPods AirPods pro Charging Case Charging cable) ."}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=17, version=3, score=0.32155183, payload={'text': 'Redragon GS590 Wireless RGB Desktop Speakers, 2.0 PC Computer Stereo Speaker w/BT 5.0/AUX/USB Mode, Compact Size, Back Ambient RGB Backlight and Easy-Access in-line Control Box, USB Powered Wireless Freedom Play - 5.0 Bluetooth wireless connection adopted for premium lossless sound quality, stable and no-delay audio transmission makes you get 100% enjoyment with your playlists from your phone, tablet or laptop. Back Vibe RGB - The refreshing design of psychedelic ambient RGB light on the back of the speakers, delivers an attractive mystery gaming vibe. 3 modes are selectable for different ambiances by touch-control, switch off the light is also available. More Than Compact - Minimalist compact design with solid frame keeps it in a calm and low key style. Up to 37 inches cable length between the two sound units compatible for most desk devices. In-Line Control Box- Delicate and compact in-line control box with audio/backlight/mode control, for supreme using convenience. Extra headphone jack take care of your private listening needs. Plug & Play for Broad Compatibility - USB powered USB sound card and AUX wired mode offers stable audio transmission, which allows this rockstar to party on wide type of stages for PC, TV, Laptop and other devices.'}, vector=None, shard_key=None, order_value=None)]

In [9]:
response = qdrant_client.scroll( collection_name="Amazon-items-collection-01",
                                offset=None,
                                limit=5,
                                with_payload=True,
                                with_vectors=False

                                )

In [29]:
response

([Record(id=0, payload={'text': 'iPhone Charger, 3Pack 3FT MFi Certified Lightning Cable Fast Charging Cord Compatible with iPhone 14 13 12 11 XS XR X Pro Max Mini 8 7 6S 6 Plus 5S SE iPad iPod AirPods… ⚡3 Pack 3 FT Charger Cable - In the Package, you will get 3 pack 3 ft USB-A to Lightning Fast Charging Cord, 3ft charging cable makes convenient to charge your device in bedroom, sofa, office, back seat of car, travel. Keep a cable in your home or office as a backup, avoid the trouble of having only one data cable. ⚡Durable Material - iPhone lightning cable with pure copper core and premium TPE surface greatly improve charging efficency and durability. With 20000+ bend lifespan test in the laboratory environment and superior functionality under heavy daily usage, the iPhone charging cord could provide with a long time service. ⚡High Speed Data Sync & Charge - Certified cable provides a fast, secure and stable charging solution for your Apple devices. It provides a safer charging current, supports maximum transfer rate up to 480Mbs and high-speed charging up to 2.4 A, which enhance the charging efficiency. ⚡Wide Compatible with iPhone Devices - MFi Certified lightniing cable compatible with iPhone 14/13/12/11/XS/XR/X/8 Plus/8/7 Plus/7/6s Plus/ 6s/6 Plus /6/5s/5c 5/iPad Pro/ iPad Air/Air 2/iPad mini/mini 2/mini 4 /iPad 4th gen/iPod Touch 5th gen/iPod nano 7th gen and Beats Pill+. ⚡Thoughtful After-sales Service - If you have any questions with our iphone charger cable, please feel free to contact our after-sales Service. Our service team will provide you with a satisfactory solution within 24 hours.'}, vector=None, shard_key=None, order_value=None),
  Record(id=1, payload={'text': 'HALLEAST for Galaxy Buds 2 Pro Case 2022/ Galaxy Buds 2 Case 2021/ Galaxy Buds Pro Case 2021/ Galaxy Buds Live Case 2020, TPU Cover Metal Alloy Carrying Case with Keychain Clip, Purple 【PREMIUM TPU & METAL】Can\'t wait to unpack and enjoy your new 2022 galaxy buds 2 pro earbuds, but you are afraid that the charging case will be scarred in a few days? HALLEAST Galaxy Buds 2 Pro Live case provides it with comprehensive protection. It is made of high quality lint-free scratch-proof TPU and shock-proof strong alloy metal with high toughness. 【COMPATIBLE MODELS】This TPU case cover specially designed for Samsung Galaxy Buds 2 Pro Case 2022/ Galaxy Buds 2 Case 2021/ Galaxy Buds Pro Case 2021/ Galaxy Buds Live Case 2020. Not compatible with Galaxy Buds (2019) and Galaxy Buds Plus (2020). 【PERFECT FIT】Snugly cover your galaxy buds 2/ pro/ live case and fit well to provide secure 360° all-round protection. The earbuds charging case can be fully opened up to 90°, very easy to take out and put in. A great birthday gift and a holiday gift. (NOTE: the earbuds and charging case NOT included.) 【SUPPORT WIRELESS CHARGING】This compatible Samsung Galaxy Buds2 Pro Case 2022/ Galaxy Buds2 Case 2021/ Galaxy Buds Pro 2021/ Live 2020 case cover fully supports wireless charging without any interference and the LED indicator is visible. It is also convenient to charge the Galaxy Buds Live via the charging cable without removing the case. (NOTE: The notched side of the top cover is the back, which is on the same side as the charging port.) 【RISK-FREE SHOPPING】 You are always welcome to contact us for any questions, we will provide the best service to make you smile. For more accessories offered by silicone maid LLC, please search store "silicone maid LLC” or brand “HALLEAST”.'}, vector=None, shard_key=None, order_value=None),
  Record(id=2, payload={'text': 'CyberpowerPC Gamer Xtreme VR Gaming PC, Intel Core i9-13900KF 3.0GHz, GeForce RTX 3070 Ti 8GB, 16GB DDR5, 1TB NVMe SSD, WiFi & Win 11 Home (GXiVR8080A33) System: Intel Core i9-13900KF 3.0GHz 8+16 Cores | Intel Z690 Chipset | 16GB DDR5 | 1TB PCIe NVMe SSD | Genuine Windows 11 Home 64-bit Graphics: NVIDIA GeForce RTX 3070 Ti 8GB Video Card | 1x HDMI | 2x DisplayPort Connectivity: 6 x USB 3.1 | 2 x USB 2.0 | 1x RJ-45 Network Ethernet 10/100/1000 | 802.11AC Wi-Fi | Audio: 7.1 Channel | Keyboard and mouse Special feature: Liquid Cool CPU | Tempered Glass Side Case Panel | Custom RGB Case Lighting | 7 Colors RGB Gaming Mouse 1 year parts & labor | Free lifetime tech support'}, vector=None, shard_key=None, order_value=None),
  Record(id=3, payload={'text': 'SUPCASE Unicorn Beetle Pro Series Case for Samsung Galaxy Tab A8 10.5 Inch (2022), Full-Body Rugged Heavy Duty Case with Built-in Screen Protector (Tilt) Compatible with Samsung GalaxyTab A8 10.5 inch (2022 Release). Model: SM-X200 / SM-X205/ SM-X207 Built-in screen protector and class-leading drop protection and raised edges to protect screen and camera. Functional pop out kickstand allows easy access to your favorite shows, movies, and games while on the go. Easy access to ports and functions while port covers keep out dust and debris. Unique corner protective and shock-absorbing design protects against extreme shock and impact forces.'}, vector=None, shard_key=None, order_value=None),
  Record(id=4, payload={'text': 'Alatino 12x25 Compact Binoculars for Adults Kids, Small Binoculars for Cruise, Bird Watching, Travel, Theatre and Concerts (Green) Basic Performance - This model provides a field of view that is able to make you feel like standing at 268ft to check the target when the target is actually away from 1000 yards. Features include a clear focus without a color-changed or Edge blurred. Close Focus - Just as critically important and it is usually only equipped in the expensive model. This feature lets you see the target clearly when it is just far away from a few steps. Applicable to labels on a shelf, raccoons in your backyard, water pipes on the roof, subtitles on the screen, etc. Comfort View - The adjustable eyecups are fully considered for eyeglass wearers allowing you to see easily even with glasses in place. Also, You will enjoy the focused sight and more comfort when your eyes are resting against the eyecups if you do not wear glasses. Compact Design - These compact binoculars can be folded up and slipped into your pocket or pack easily, they can be taken anywhere because of their lightweight at 0.72lb only. The handling design makes the binoculars easy to hold and keep stably. Broad Usage - These small binoculars are used for various activities, such as bird watching, hiking, hunting, sports and other "on the go" activities. Also, they make an ideal gift for anyone who wants to enjoy close-up outside activities. Also, a strong EVA storage case (A case not the nylon bag) comes with the package.'}, vector=None, shard_key=None, order_value=None)],
 5)

In [14]:
response

([Record(id=0, payload={'text': 'iPhone Charger, 3Pack 3FT MFi Certified Lightning Cable Fast Charging Cord Compatible with iPhone 14 13 12 11 XS XR X Pro Max Mini 8 7 6S 6 Plus 5S SE iPad iPod AirPods… ⚡3 Pack 3 FT Charger Cable - In the Package, you will get 3 pack 3 ft USB-A to Lightning Fast Charging Cord, 3ft charging cable makes convenient to charge your device in bedroom, sofa, office, back seat of car, travel. Keep a cable in your home or office as a backup, avoid the trouble of having only one data cable. ⚡Durable Material - iPhone lightning cable with pure copper core and premium TPE surface greatly improve charging efficency and durability. With 20000+ bend lifespan test in the laboratory environment and superior functionality under heavy daily usage, the iPhone charging cord could provide with a long time service. ⚡High Speed Data Sync & Charge - Certified cable provides a fast, secure and stable charging solution for your Apple devices. It provides a safer charging current, supports maximum transfer rate up to 480Mbs and high-speed charging up to 2.4 A, which enhance the charging efficiency. ⚡Wide Compatible with iPhone Devices - MFi Certified lightniing cable compatible with iPhone 14/13/12/11/XS/XR/X/8 Plus/8/7 Plus/7/6s Plus/ 6s/6 Plus /6/5s/5c 5/iPad Pro/ iPad Air/Air 2/iPad mini/mini 2/mini 4 /iPad 4th gen/iPod Touch 5th gen/iPod nano 7th gen and Beats Pill+. ⚡Thoughtful After-sales Service - If you have any questions with our iphone charger cable, please feel free to contact our after-sales Service. Our service team will provide you with a satisfactory solution within 24 hours.'}, vector=None, shard_key=None, order_value=None),
  Record(id=1, payload={'text': 'HALLEAST for Galaxy Buds 2 Pro Case 2022/ Galaxy Buds 2 Case 2021/ Galaxy Buds Pro Case 2021/ Galaxy Buds Live Case 2020, TPU Cover Metal Alloy Carrying Case with Keychain Clip, Purple 【PREMIUM TPU & METAL】Can\'t wait to unpack and enjoy your new 2022 galaxy buds 2 pro earbuds, but you are afraid that the charging case will be scarred in a few days? HALLEAST Galaxy Buds 2 Pro Live case provides it with comprehensive protection. It is made of high quality lint-free scratch-proof TPU and shock-proof strong alloy metal with high toughness. 【COMPATIBLE MODELS】This TPU case cover specially designed for Samsung Galaxy Buds 2 Pro Case 2022/ Galaxy Buds 2 Case 2021/ Galaxy Buds Pro Case 2021/ Galaxy Buds Live Case 2020. Not compatible with Galaxy Buds (2019) and Galaxy Buds Plus (2020). 【PERFECT FIT】Snugly cover your galaxy buds 2/ pro/ live case and fit well to provide secure 360° all-round protection. The earbuds charging case can be fully opened up to 90°, very easy to take out and put in. A great birthday gift and a holiday gift. (NOTE: the earbuds and charging case NOT included.) 【SUPPORT WIRELESS CHARGING】This compatible Samsung Galaxy Buds2 Pro Case 2022/ Galaxy Buds2 Case 2021/ Galaxy Buds Pro 2021/ Live 2020 case cover fully supports wireless charging without any interference and the LED indicator is visible. It is also convenient to charge the Galaxy Buds Live via the charging cable without removing the case. (NOTE: The notched side of the top cover is the back, which is on the same side as the charging port.) 【RISK-FREE SHOPPING】 You are always welcome to contact us for any questions, we will provide the best service to make you smile. For more accessories offered by silicone maid LLC, please search store "silicone maid LLC” or brand “HALLEAST”.'}, vector=None, shard_key=None, order_value=None),
  Record(id=2, payload={'text': 'CyberpowerPC Gamer Xtreme VR Gaming PC, Intel Core i9-13900KF 3.0GHz, GeForce RTX 3070 Ti 8GB, 16GB DDR5, 1TB NVMe SSD, WiFi & Win 11 Home (GXiVR8080A33) System: Intel Core i9-13900KF 3.0GHz 8+16 Cores | Intel Z690 Chipset | 16GB DDR5 | 1TB PCIe NVMe SSD | Genuine Windows 11 Home 64-bit Graphics: NVIDIA GeForce RTX 3070 Ti 8GB Video Card | 1x HDMI | 2x DisplayPort Connectivity: 6 x USB 3.1 | 2 x USB 2.0 | 1x RJ-45 Network Ethernet 10/100/1000 | 802.11AC Wi-Fi | Audio: 7.1 Channel | Keyboard and mouse Special feature: Liquid Cool CPU | Tempered Glass Side Case Panel | Custom RGB Case Lighting | 7 Colors RGB Gaming Mouse 1 year parts & labor | Free lifetime tech support'}, vector=None, shard_key=None, order_value=None),
  Record(id=3, payload={'text': 'SUPCASE Unicorn Beetle Pro Series Case for Samsung Galaxy Tab A8 10.5 Inch (2022), Full-Body Rugged Heavy Duty Case with Built-in Screen Protector (Tilt) Compatible with Samsung GalaxyTab A8 10.5 inch (2022 Release). Model: SM-X200 / SM-X205/ SM-X207 Built-in screen protector and class-leading drop protection and raised edges to protect screen and camera. Functional pop out kickstand allows easy access to your favorite shows, movies, and games while on the go. Easy access to ports and functions while port covers keep out dust and debris. Unique corner protective and shock-absorbing design protects against extreme shock and impact forces.'}, vector=None, shard_key=None, order_value=None),
  Record(id=4, payload={'text': 'Alatino 12x25 Compact Binoculars for Adults Kids, Small Binoculars for Cruise, Bird Watching, Travel, Theatre and Concerts (Green) Basic Performance - This model provides a field of view that is able to make you feel like standing at 268ft to check the target when the target is actually away from 1000 yards. Features include a clear focus without a color-changed or Edge blurred. Close Focus - Just as critically important and it is usually only equipped in the expensive model. This feature lets you see the target clearly when it is just far away from a few steps. Applicable to labels on a shelf, raccoons in your backyard, water pipes on the roof, subtitles on the screen, etc. Comfort View - The adjustable eyecups are fully considered for eyeglass wearers allowing you to see easily even with glasses in place. Also, You will enjoy the focused sight and more comfort when your eyes are resting against the eyecups if you do not wear glasses. Compact Design - These compact binoculars can be folded up and slipped into your pocket or pack easily, they can be taken anywhere because of their lightweight at 0.72lb only. The handling design makes the binoculars easy to hold and keep stably. Broad Usage - These small binoculars are used for various activities, such as bird watching, hiking, hunting, sports and other "on the go" activities. Also, they make an ideal gift for anyone who wants to enjoy close-up outside activities. Also, a strong EVA storage case (A case not the nylon bag) comes with the package.'}, vector=None, shard_key=None, order_value=None)],
 5)

In [18]:
type(response[0][0].payload.get("text"))

str

In [27]:
metadata = {k: v for k, v in response[0][0].payload.items() if k =='text'}
print(metadata)

{'text': 'iPhone Charger, 3Pack 3FT MFi Certified Lightning Cable Fast Charging Cord Compatible with iPhone 14 13 12 11 XS XR X Pro Max Mini 8 7 6S 6 Plus 5S SE iPad iPod AirPods… ⚡3 Pack 3 FT Charger Cable - In the Package, you will get 3 pack 3 ft USB-A to Lightning Fast Charging Cord, 3ft charging cable makes convenient to charge your device in bedroom, sofa, office, back seat of car, travel. Keep a cable in your home or office as a backup, avoid the trouble of having only one data cable. ⚡Durable Material - iPhone lightning cable with pure copper core and premium TPE surface greatly improve charging efficency and durability. With 20000+ bend lifespan test in the laboratory environment and superior functionality under heavy daily usage, the iPhone charging cord could provide with a long time service. ⚡High Speed Data Sync & Charge - Certified cable provides a fast, secure and stable charging solution for your Apple devices. It provides a safer charging current, supports maximum transfer rate up to 480Mbs and high-speed charging up to 2.4 A, which enhance the charging efficiency. ⚡Wide Compatible with iPhone Devices - MFi Certified lightniing cable compatible with iPhone 14/13/12/11/XS/XR/X/8 Plus/8/7 Plus/7/6s Plus/ 6s/6 Plus /6/5s/5c 5/iPad Pro/ iPad Air/Air 2/iPad mini/mini 2/mini 4 /iPad 4th gen/iPod Touch 5th gen/iPod nano 7th gen and Beats Pill+. ⚡Thoughtful After-sales Service - If you have any questions with our iphone charger cable, please feel free to contact our after-sales Service. Our service team will provide you with a satisfactory solution within 24 hours.'}

In [ ]:
for point in response[0]:
    id = point.id
    text = point.payload.get("text")