In [66]:
from qdrant_client import QdrantClient, models
from qdrant_client.models import (
    PointStruct,
    VectorParams,
    PayloadSchemaType,
    Distance,
    Prefetch, Filter, FieldCondition, MatchText, FusionQuery,
    SparseVectorParams,
    Document,
    MatchAny
    
)
import pandas as pd
import openai
from openai import OpenAI
from dotenv import load_dotenv
import fastembed
import numpy as np
import pandas as pd
import tiktoken

In [2]:
load_dotenv() # This loads the variables from a .env file in the current or parent directories

qdrant_client = QdrantClient(
    url="https://511b707b-5120-4c5e-8f7f-cb3a72cb82f4.us-west-2-0.aws.cloud.qdrant.io:6333", 
    api_key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.9BuL_6z6hC7gHfXmMOB2SvlWtM3t6wchSuocbm-6MHE",
)
print(qdrant_client.get_collections())

collections=[CollectionDescription(name='Amazon-items-collection-02-hybrid-search'), CollectionDescription(name='Amazon-items-collection-01-hybrid')]

In [6]:
dummy_vector = np.zeros(1536).tolist()

In [8]:
payload = qdrant_client.query_points(
    collection_name="Amazon-items-collection-02-hybrid-search",
    query=dummy_vector,
    using="text-embedding-3-small",
    limit=1000,
    with_payload=["parent_asin"],
    with_vectors=False
)

In [9]:
payload.points

[ScoredPoint(id=3, version=1, score=0.0, payload={'parent_asin': 'B0BZ5R7CVP'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=4, version=1, score=0.0, payload={'parent_asin': 'B09PFSVK44'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=5, version=1, score=0.0, payload={'parent_asin': 'B0BYYLJRHT'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=6, version=1, score=0.0, payload={'parent_asin': 'B0B1MPKCS8'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=7, version=1, score=0.0, payload={'parent_asin': 'B0B14HTZ59'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=8, version=1, score=0.0, payload={'parent_asin': 'B0BB1YKXL1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=9, version=1, score=0.0, payload={'parent_asin': 'B09TNXY54Y'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=10, version=1, score=0.0, payload={'parent_asin': 'B0CF57H28T'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=11, version=1, score=0.0, payload={'parent_asin': 'B0BLV7YH2W'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=12, version=1, score=0.0, payload={'parent_asin': 'B0C9XFF3CT'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=13, version=1, score=0.0, payload={'parent_asin': 'B0C6K1GQCF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=14, version=1, score=0.0, payload={'parent_asin': 'B0BY2ZBRZD'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=15, version=1, score=0.0, payload={'parent_asin': 'B0BGLRMPQD'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=16, version=1, score=0.0, payload={'parent_asin': 'B0BNN776VN'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=17, version=1, score=0.0, payload={'parent_asin': 'B09QGNB537'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=18, version=1, score=0.0, payload={'parent_asin': 'B08BX2L8F2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=19, version=1, score=0.0, payload={'parent_asin': 'B0BG5L2YLC'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=20, version=1, score=0.0, payload={'parent_asin': 'B0C4DBSWGW'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=21, version=1, score=0.0, payload={'parent_asin': 'B0CBMPG524'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=22, version=1, score=0.0, payload={'parent_asin': 'B09WCFC5D9'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=23, version=1, score=0.0, payload={'parent_asin': 'B0CF1WM24K'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=24, version=1, score=0.0, payload={'parent_asin': 'B0BS15TRJ3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=25, version=1, score=0.0, payload={'parent_asin': 'B0BV6PWVCG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=26, version=1, score=0.0, payload={'parent_asin': 'B0BR8Q2PXN'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=27, version=1, score=0.0, payload={'parent_asin': 'B09PYFMTBF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=28, version=1, score=0.0, payload={'parent_asin': 'B0BP9Z159S'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=29, version=1, score=0.0, payload={'parent_asin': 'B09XCKYXR8'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=30, version=1, score=0.0, payload={'parent_asin': 'B0B2JJJFCD'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=31, version=1, score=0.0, payload={'parent_asin': 'B0BFPZGYLD'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=32, version=1, score=0.0, payload={'parent_asin': 'B09SHNKDBC'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=33, version=1, score=0.0, payload={'parent_asin': 'B0B3MMP22L'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=34, version=1, score=0.0, payload={'parent_asin': 'B0BNHVLF7G'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=35, version=1, score=0.0, payload={'parent_asin': 'B0B8BY5HCG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=36, version=1, score=0.0, payload={'parent_asin': 'B09ZPV8WBV'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=37, version=1, score=0.0, payload={'parent_asin': 'B0BNVKS9WH'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=38, version=1, score=0.0, payload={'parent_asin': 'B09PRK49JH'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=39, version=1, score=0.0, payload={'parent_asin': 'B0CGM29ZL7'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=40, version=1, score=0.0, payload={'parent_asin': 'B0C142QS8X'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=41, version=1, score=0.0, payload={'parent_asin': 'B08BR9X387'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=42, version=1, score=0.0, payload={'parent_asin': 'B0CH6P8DYF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=43, version=1, score=0.0, payload={'parent_asin': 'B0BGDQLZD2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=44, version=1, score=0.0, payload={'parent_asin': 'B0B55TZLBR'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=45, version=1, score=0.0, payload={'parent_asin': 'B0B9FTVL58'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=46, version=1, score=0.0, payload={'parent_asin': 'B09LVX3XW2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=47, version=1, score=0.0, payload={'parent_asin': 'B09Y39DSWR'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=48, version=1, score=0.0, payload={'parent_asin': 'B0B6V8THVX'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=49, version=1, score=0.0, payload={'parent_asin': 'B0B67ZFRPC'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=50, version=1, score=0.0, payload={'parent_asin': 'B0B7495RL6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=51, version=1, score=0.0, payload={'parent_asin': 'B096XB5Q1T'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=52, version=1, score=0.0, payload={'parent_asin': 'B09DK8NK6G'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=53, version=1, score=0.0, payload={'parent_asin': 'B0B68DHY1J'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=54, version=1, score=0.0, payload={'parent_asin': 'B09XX27FH2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=55, version=1, score=0.0, payload={'parent_asin': 'B0BJW1SRG5'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=56, version=1, score=0.0, payload={'parent_asin': 'B0BK14FQMQ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=57, version=1, score=0.0, payload={'parent_asin': 'B0BY9QNXFH'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=58, version=1, score=0.0, payload={'parent_asin': 'B09Y77N1T2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=59, version=1, score=0.0, payload={'parent_asin': 'B0BYH466CM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=60, version=1, score=0.0, payload={'parent_asin': 'B09SKRR2MF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=61, version=1, score=0.0, payload={'parent_asin': 'B0BXRSFB93'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=62, version=1, score=0.0, payload={'parent_asin': 'B09MFM19SV'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=63, version=1, score=0.0, payload={'parent_asin': 'B0B9MPGXDL'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=64, version=1, score=0.0, payload={'parent_asin': 'B09GNFDH9M'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=65, version=1, score=0.0, payload={'parent_asin': 'B09XDNPQHZ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=66, version=1, score=0.0, payload={'parent_asin': 'B0BP68QCZ2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=67, version=1, score=0.0, payload={'parent_asin': 'B09SSZNWQD'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=68, version=1, score=0.0, payload={'parent_asin': 'B0BVTCG71C'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=69, version=1, score=0.0, payload={'parent_asin': 'B09PQ97H3G'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=70, version=1, score=0.0, payload={'parent_asin': 'B0BLYCBGMF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=71, version=1, score=0.0, payload={'parent_asin': 'B0BPS9F24C'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=72, version=1, score=0.0, payload={'parent_asin': 'B0BXRWX9RN'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=73, version=1, score=0.0, payload={'parent_asin': 'B0B8G6QW6X'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=74, version=1, score=0.0, payload={'parent_asin': 'B0C3XYD574'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=75, version=1, score=0.0, payload={'parent_asin': 'B0BYSY8NXV'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=76, version=1, score=0.0, payload={'parent_asin': 'B0B6KMRN9B'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=77, version=1, score=0.0, payload={'parent_asin': 'B0BC78N85F'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=78, version=1, score=0.0, payload={'parent_asin': 'B0BCCCNHD8'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=79, version=1, score=0.0, payload={'parent_asin': 'B09GNF94GQ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=80, version=1, score=0.0, payload={'parent_asin': 'B0BZQ5YKKY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=81, version=1, score=0.0, payload={'parent_asin': 'B0C6Y8Q2S1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=82, version=1, score=0.0, payload={'parent_asin': 'B09CCL371W'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=83, version=1, score=0.0, payload={'parent_asin': 'B0C7Q3X76Q'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=84, version=1, score=0.0, payload={'parent_asin': 'B0B2C5RDV6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=85, version=1, score=0.0, payload={'parent_asin': 'B09PN99MN9'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=86, version=1, score=0.0, payload={'parent_asin': 'B09TF5WK26'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=87, version=1, score=0.0, payload={'parent_asin': 'B0BFDH4NX1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=88, version=1, score=0.0, payload={'parent_asin': 'B0CJ8SDWZP'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=89, version=1, score=0.0, payload={'parent_asin': 'B0C8592NWX'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=90, version=1, score=0.0, payload={'parent_asin': 'B0BBM919DP'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=91, version=1, score=0.0, payload={'parent_asin': 'B0B5W5NKKN'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=92, version=1, score=0.0, payload={'parent_asin': 'B09PYN3P4B'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=93, version=1, score=0.0, payload={'parent_asin': 'B099K711GD'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=94, version=1, score=0.0, payload={'parent_asin': 'B09YTGFYZK'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=95, version=1, score=0.0, payload={'parent_asin': 'B09MF44Q7C'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=96, version=1, score=0.0, payload={'parent_asin': 'B0BVPZNQBG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=97, version=1, score=0.0, payload={'parent_asin': 'B0BT344Q4K'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=98, version=1, score=0.0, payload={'parent_asin': 'B0BY1ZYQPQ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=99, version=1, score=0.0, payload={'parent_asin': 'B0BN8Q1Z9S'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=100, version=1, score=0.0, payload={'parent_asin': 'B0BBPVCFW7'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=101, version=1, score=0.0, payload={'parent_asin': 'B0BWVD7KZG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=102, version=1, score=0.0, payload={'parent_asin': 'B0C16S18PX'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=103, version=1, score=0.0, payload={'parent_asin': 'B0CB7J8KN4'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=104, version=1, score=0.0, payload={'parent_asin': 'B0BBY5TGTM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=105, version=1, score=0.0, payload={'parent_asin': 'B09YLWM325'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=106, version=1, score=0.0, payload={'parent_asin': 'B0B65DXSCJ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=107, version=1, score=0.0, payload={'parent_asin': 'B0C7HFJR2K'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=108, version=1, score=0.0, payload={'parent_asin': 'B0BGMYY12Z'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=109, version=1, score=0.0, payload={'parent_asin': 'B0C595QFS9'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=110, version=1, score=0.0, payload={'parent_asin': 'B0B6PKDSMN'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=111, version=1, score=0.0, payload={'parent_asin': 'B09QKT9QZ6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=112, version=1, score=0.0, payload={'parent_asin': 'B09XV39FHL'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=113, version=1, score=0.0, payload={'parent_asin': 'B09QLKN43H'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=114, version=1, score=0.0, payload={'parent_asin': 'B0CJ66R5H2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=115, version=1, score=0.0, payload={'parent_asin': 'B08D8Z9LPW'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=116, version=1, score=0.0, payload={'parent_asin': 'B0CB1MT9WD'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=117, version=1, score=0.0, payload={'parent_asin': 'B0BQYN54PZ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=118, version=1, score=0.0, payload={'parent_asin': 'B07MZK432D'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=119, version=1, score=0.0, payload={'parent_asin': 'B0BMVR2MVC'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=120, version=1, score=0.0, payload={'parent_asin': 'B09R1TMXR3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=121, version=1, score=0.0, payload={'parent_asin': 'B0C5J4S25S'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=122, version=1, score=0.0, payload={'parent_asin': 'B0BTDJ6FBR'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=123, version=1, score=0.0, payload={'parent_asin': 'B0BZP7BM9R'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=124, version=1, score=0.0, payload={'parent_asin': 'B09Q345B29'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=125, version=1, score=0.0, payload={'parent_asin': 'B09RV6KSMH'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=126, version=1, score=0.0, payload={'parent_asin': 'B0BC426455'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=127, version=1, score=0.0, payload={'parent_asin': 'B0BDRD5TRX'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=128, version=1, score=0.0, payload={'parent_asin': 'B0BJJYFRLF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=129, version=1, score=0.0, payload={'parent_asin': 'B09SPBM7D3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=130, version=1, score=0.0, payload={'parent_asin': 'B09RWW247J'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=131, version=1, score=0.0, payload={'parent_asin': 'B0BJK7YRCB'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=132, version=1, score=0.0, payload={'parent_asin': 'B0B4V7XW21'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=133, version=1, score=0.0, payload={'parent_asin': 'B0BNPVBZPG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=134, version=1, score=0.0, payload={'parent_asin': 'B0C7RF6YTR'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=135, version=1, score=0.0, payload={'parent_asin': 'B0BRXZDBXZ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=136, version=1, score=0.0, payload={'parent_asin': 'B0BP1YXF3R'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=137, version=1, score=0.0, payload={'parent_asin': 'B0C6PGF8BV'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=138, version=1, score=0.0, payload={'parent_asin': 'B0BYSRTQNQ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=139, version=1, score=0.0, payload={'parent_asin': 'B0BSS319BG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=140, version=1, score=0.0, payload={'parent_asin': 'B0BL3YGC62'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=141, version=1, score=0.0, payload={'parent_asin': 'B09YJ2867L'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=142, version=1, score=0.0, payload={'parent_asin': 'B0B1MZT835'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=143, version=1, score=0.0, payload={'parent_asin': 'B0C37GVWBP'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=144, version=1, score=0.0, payload={'parent_asin': 'B0C772GZRF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=145, version=1, score=0.0, payload={'parent_asin': 'B09YPWNBKZ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=146, version=1, score=0.0, payload={'parent_asin': 'B0BXNP7DYW'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=147, version=1, score=0.0, payload={'parent_asin': 'B0C4W4XMVZ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=148, version=1, score=0.0, payload={'parent_asin': 'B0CGHVQ4M3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=149, version=1, score=0.0, payload={'parent_asin': 'B0BJDVXB6T'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=150, version=1, score=0.0, payload={'parent_asin': 'B0B934RS5N'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=151, version=1, score=0.0, payload={'parent_asin': 'B09TD2WR6H'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=152, version=1, score=0.0, payload={'parent_asin': 'B09V18BFYL'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=153, version=1, score=0.0, payload={'parent_asin': 'B0BJK3V3P4'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=154, version=1, score=0.0, payload={'parent_asin': 'B0B4B45CYV'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=155, version=1, score=0.0, payload={'parent_asin': 'B09V9P7Z1T'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=156, version=1, score=0.0, payload={'parent_asin': 'B0BTYQ7VVM'}, vector=None, shard_key=None, order_value=None),

In [10]:
parent_asin_list = [item.payload['parent_asin'] for item in payload.points]

In [12]:
len(parent_asin_list)

500

In [14]:
df_reviews = pd.read_json("/Users/neeleshsethi/Documents/datascience/ai-agents/ai-agents/data/Electornics_2022_2023_with_category_ratings_100_sample_1000.jsonl", lines=True)

In [21]:
df_reviews_sample = df_reviews[df_reviews['parent_asin'].isin(parent_asin_list)]

In [22]:
df_reviews_sample.shape

(45948, 10)

In [23]:
def preprocess_reviews_data(row):
    return f"{row['title']} {row['text']}"

In [24]:
def token_count(row, model="text-embedding-3-small" ):
    encoding = tiktoken.encoding_for_model(model)
    encode_my_data = encoding.encode(row['preprocessed_data'])
    return len(encode_my_data)

In [25]:
df_reviews_sample['preprocessed_data'] = df_reviews_sample.apply(preprocess_reviews_data, axis=1)

/var/folders/0d/_j5c1nk133xfpm611lvlyw6m0000gn/T/ipykernel_86363/3928544976.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_reviews_sample['preprocessed_data'] = df_reviews_sample.apply(preprocess_reviews_data, axis=1)

In [26]:
df_reviews_sample.head(5)

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,preprocessed_data
0,5,Perfect!,This is perfect! Thank you so much!!! I absolu...,[],B09992M2LX,B09ZPV8WBV,AHX4XWVVQUKT3FCNWCVASDF4Q56Q,2022-08-05 04:06:39.589,0,True,Perfect! This is perfect! Thank you so much!!!...
1,5,3ft mini usb cables,I don't have many things that still use a mini...,[],B09Y94B2NM,B09Y95BMKX,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2022-07-16 16:03:28.714,3,True,3ft mini usb cables I don't have many things t...
10,5,Great privacy screen!,I've tried a few different privacy screens for...,[],B0B7LGQ836,B0C65RMTNV,AHUPTBY3F3UN2S5H7K5JLP6MAV5Q,2023-01-20 23:08:45.699,0,False,Great privacy screen! I've tried a few differe...
11,1,Didn't work,Doesn't pair with any device.,[],B0B979SXNT,B0BGRL2618,AHHFW36BP4VMQWC6V2NTKIXFAA2A,2023-01-02 01:29:08.702,0,True,Didn't work Doesn't pair with any device.
12,4,Sony's Midrange ANC Buds,I have worked a lot with active noise cancelin...,[],B09YL76VSR,B0BJS6CXDN,AFLX66DKF6R3H6OEOC3TIVAYXZIQ,2022-06-26 10:58:20.816,0,False,Sony's Midrange ANC Buds I have worked a lot w...

In [27]:
df_reviews_sample['preprocessed_data_token_count'] = df_reviews_sample.apply(token_count, axis=1)

/var/folders/0d/_j5c1nk133xfpm611lvlyw6m0000gn/T/ipykernel_86363/2074138920.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_reviews_sample['preprocessed_data_token_count'] = df_reviews_sample.apply(token_count, axis=1)

In [28]:
df_reviews_sample.head(5)

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,preprocessed_data,preprocessed_data_token_count
0,5,Perfect!,This is perfect! Thank you so much!!! I absolu...,[],B09992M2LX,B09ZPV8WBV,AHX4XWVVQUKT3FCNWCVASDF4Q56Q,2022-08-05 04:06:39.589,0,True,Perfect! This is perfect! Thank you so much!!!...,21
1,5,3ft mini usb cables,I don't have many things that still use a mini...,[],B09Y94B2NM,B09Y95BMKX,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2022-07-16 16:03:28.714,3,True,3ft mini usb cables I don't have many things t...,114
10,5,Great privacy screen!,I've tried a few different privacy screens for...,[],B0B7LGQ836,B0C65RMTNV,AHUPTBY3F3UN2S5H7K5JLP6MAV5Q,2023-01-20 23:08:45.699,0,False,Great privacy screen! I've tried a few differe...,89
11,1,Didn't work,Doesn't pair with any device.,[],B0B979SXNT,B0BGRL2618,AHHFW36BP4VMQWC6V2NTKIXFAA2A,2023-01-02 01:29:08.702,0,True,Didn't work Doesn't pair with any device.,11
12,4,Sony's Midrange ANC Buds,I have worked a lot with active noise cancelin...,[],B09YL76VSR,B0BJS6CXDN,AFLX66DKF6R3H6OEOC3TIVAYXZIQ,2022-06-26 10:58:20.816,0,False,Sony's Midrange ANC Buds I have worked a lot w...,478

In [30]:
total_tokens = df_reviews_sample['preprocessed_data_token_count'].sum()
total_tokens

np.int64(2839931)

In [31]:
qdrant_client.create_collection(
    collection_name="Amazon-items-collection-01-reviews",
    vectors_config=VectorParams(size=1536, distance=Distance.COSINE)
)

True

In [32]:
qdrant_client.create_payload_index(
        collection_name="Amazon-items-collection-01-reviews",
        field_name="parent_asin",
        field_schema=PayloadSchemaType.KEYWORD

)

UpdateResult(operation_id=1, status=<UpdateStatus.COMPLETED: 'completed'>)

In [35]:
def get_embeddings_batch(text_list,model="text-embedding-3-small",batch_size=100 ):
    if len(text_list) < batch_size:
        response = openai.embeddings.create(input=text_list, model=model)
        return [embedding.embedding for embedding in response.data]

    all_embeddings = []

    counter = 1
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i+batch_size]
        response = openai.embeddings.create(input=batch, model=model)
        batch_embedding_flatten = [embedding.embedding for embedding in response.data]
        all_embeddings.extend(batch_embedding_flatten)
        print(f"Embedding for batch {counter*batch_size} is complete out of {len(text_list)}")
        counter = counter + 1
    return all_embeddings

In [46]:
data_to_embed_review = df_reviews_sample[['preprocessed_data', 'parent_asin']].to_dict(orient='records')

In [48]:
data_to_embed_review[0]

{'preprocessed_data': 'Perfect! This is perfect! Thank you so much!!! I absolutely love it!!! It’s great quality!!!',
 'parent_asin': 'B09ZPV8WBV'}

In [50]:
text_to_embed_reviews = [data['preprocessed_data'] for data in data_to_embed_review]

In [51]:
text_to_embed_reviews[0:2]

['Perfect! This is perfect! Thank you so much!!! I absolutely love it!!! It’s great quality!!!',
 "3ft mini usb cables I don't have many things that still use a mini USB charger cable, but I after a while you have to replace the charger cables.  These seem to work well and it was noted in the ad that they are reinforced at the head area to prolong life.  We shall see - time will tell.  I never hesitate to update my reviews should new info seem useful.  I do not accept any discounts or deals that are not available to all shoppers. And my reviews are based purely on my personal experience with each item I review."]

In [52]:
embedding_reviews = get_embeddings_batch(text_to_embed_reviews, batch_size=500)

Embedding for batch 500 is complete out of 45948
Embedding for batch 1000 is complete out of 45948
Embedding for batch 1500 is complete out of 45948
Embedding for batch 2000 is complete out of 45948
Embedding for batch 2500 is complete out of 45948
Embedding for batch 3000 is complete out of 45948
Embedding for batch 3500 is complete out of 45948
Embedding for batch 4000 is complete out of 45948
Embedding for batch 4500 is complete out of 45948
Embedding for batch 5000 is complete out of 45948
Embedding for batch 5500 is complete out of 45948
Embedding for batch 6000 is complete out of 45948
Embedding for batch 6500 is complete out of 45948
Embedding for batch 7000 is complete out of 45948
Embedding for batch 7500 is complete out of 45948
Embedding for batch 8000 is complete out of 45948
Embedding for batch 8500 is complete out of 45948
Embedding for batch 9000 is complete out of 45948
Embedding for batch 9500 is complete out of 45948
Embedding for batch 10000 is complete out of 45948
Embedding for batch 10500 is complete out of 45948
Embedding for batch 11000 is complete out of 45948
Embedding for batch 11500 is complete out of 45948
Embedding for batch 12000 is complete out of 45948
Embedding for batch 12500 is complete out of 45948
Embedding for batch 13000 is complete out of 45948
Embedding for batch 13500 is complete out of 45948
Embedding for batch 14000 is complete out of 45948
Embedding for batch 14500 is complete out of 45948
Embedding for batch 15000 is complete out of 45948
Embedding for batch 15500 is complete out of 45948
Embedding for batch 16000 is complete out of 45948
Embedding for batch 16500 is complete out of 45948
Embedding for batch 17000 is complete out of 45948
Embedding for batch 17500 is complete out of 45948
Embedding for batch 18000 is complete out of 45948
Embedding for batch 18500 is complete out of 45948
Embedding for batch 19000 is complete out of 45948
Embedding for batch 19500 is complete out of 45948
Embedding for batch 20000 is complete out of 45948
Embedding for batch 20500 is complete out of 45948
Embedding for batch 21000 is complete out of 45948
Embedding for batch 21500 is complete out of 45948
Embedding for batch 22000 is complete out of 45948
Embedding for batch 22500 is complete out of 45948
Embedding for batch 23000 is complete out of 45948
Embedding for batch 23500 is complete out of 45948
Embedding for batch 24000 is complete out of 45948
Embedding for batch 24500 is complete out of 45948
Embedding for batch 25000 is complete out of 45948
Embedding for batch 25500 is complete out of 45948
Embedding for batch 26000 is complete out of 45948
Embedding for batch 26500 is complete out of 45948
Embedding for batch 27000 is complete out of 45948
Embedding for batch 27500 is complete out of 45948
Embedding for batch 28000 is complete out of 45948
Embedding for batch 28500 is complete out of 45948
Embedding for batch 29000 is complete out of 45948
Embedding for batch 29500 is complete out of 45948
Embedding for batch 30000 is complete out of 45948
Embedding for batch 30500 is complete out of 45948
Embedding for batch 31000 is complete out of 45948
Embedding for batch 31500 is complete out of 45948
Embedding for batch 32000 is complete out of 45948
Embedding for batch 32500 is complete out of 45948
Embedding for batch 33000 is complete out of 45948
Embedding for batch 33500 is complete out of 45948
Embedding for batch 34000 is complete out of 45948
Embedding for batch 34500 is complete out of 45948
Embedding for batch 35000 is complete out of 45948
Embedding for batch 35500 is complete out of 45948
Embedding for batch 36000 is complete out of 45948
Embedding for batch 36500 is complete out of 45948
Embedding for batch 37000 is complete out of 45948
Embedding for batch 37500 is complete out of 45948
Embedding for batch 38000 is complete out of 45948
Embedding for batch 38500 is complete out of 45948
Embedding for batch 39000 is complete out of 45948
Embedding for batch 39500 is complete out of 45948
Embedding for batch 40000 is complete out of 45948
Embedding for batch 40500 is complete out of 45948
Embedding for batch 41000 is complete out of 45948
Embedding for batch 41500 is complete out of 45948
Embedding for batch 42000 is complete out of 45948
Embedding for batch 42500 is complete out of 45948
Embedding for batch 43000 is complete out of 45948
Embedding for batch 43500 is complete out of 45948
Embedding for batch 44000 is complete out of 45948
Embedding for batch 44500 is complete out of 45948
Embedding for batch 45000 is complete out of 45948
Embedding for batch 45500 is complete out of 45948
Embedding for batch 46000 is complete out of 45948

In [58]:
pointstructs = []
i = 1
for embedding, data in zip(embedding_reviews, data_to_embed_review):
    single_point = PointStruct(
        id=i,
        vector=embedding,
        payload={
            "text" : data['preprocessed_data'],
            "parent_asin": data['parent_asin']

        }
    )
    pointstructs.append(single_point)
    i+=1

In [61]:
batch_size_qdrant=100
counter = 1
for i in range(0, len(pointstructs),batch_size_qdrant):
    batch = pointstructs[i : i+ batch_size_qdrant]
    qdrant_client.upsert(
        collection_name="Amazon-items-collection-01-reviews",
        wait=True,
        points=batch
    )
    print(f"Processed {counter*batch_size_qdrant} out of {len(pointstructs)}")
    counter+=1

Processed 100 out of 45948
Processed 200 out of 45948
Processed 300 out of 45948
Processed 400 out of 45948
Processed 500 out of 45948
Processed 600 out of 45948
Processed 700 out of 45948
Processed 800 out of 45948
Processed 900 out of 45948
Processed 1000 out of 45948
Processed 1100 out of 45948
Processed 1200 out of 45948
Processed 1300 out of 45948
Processed 1400 out of 45948
Processed 1500 out of 45948
Processed 1600 out of 45948
Processed 1700 out of 45948
Processed 1800 out of 45948
Processed 1900 out of 45948
Processed 2000 out of 45948
Processed 2100 out of 45948
Processed 2200 out of 45948
Processed 2300 out of 45948
Processed 2400 out of 45948
Processed 2500 out of 45948
Processed 2600 out of 45948
Processed 2700 out of 45948
Processed 2800 out of 45948
Processed 2900 out of 45948
Processed 3000 out of 45948
Processed 3100 out of 45948
Processed 3200 out of 45948
Processed 3300 out of 45948
Processed 3400 out of 45948
Processed 3500 out of 45948
Processed 3600 out of 45948
Processed 3700 out of 45948
Processed 3800 out of 45948
Processed 3900 out of 45948
Processed 4000 out of 45948
Processed 4100 out of 45948
Processed 4200 out of 45948
Processed 4300 out of 45948
Processed 4400 out of 45948
Processed 4500 out of 45948
Processed 4600 out of 45948
Processed 4700 out of 45948
Processed 4800 out of 45948
Processed 4900 out of 45948
Processed 5000 out of 45948
Processed 5100 out of 45948
Processed 5200 out of 45948
Processed 5300 out of 45948
Processed 5400 out of 45948
Processed 5500 out of 45948
Processed 5600 out of 45948
Processed 5700 out of 45948
Processed 5800 out of 45948
Processed 5900 out of 45948
Processed 6000 out of 45948
Processed 6100 out of 45948
Processed 6200 out of 45948
Processed 6300 out of 45948
Processed 6400 out of 45948
Processed 6500 out of 45948
Processed 6600 out of 45948
Processed 6700 out of 45948
Processed 6800 out of 45948
Processed 6900 out of 45948
Processed 7000 out of 45948
Processed 7100 out of 45948
Processed 7200 out of 45948
Processed 7300 out of 45948
Processed 7400 out of 45948
Processed 7500 out of 45948
Processed 7600 out of 45948
Processed 7700 out of 45948
Processed 7800 out of 45948
Processed 7900 out of 45948
Processed 8000 out of 45948
Processed 8100 out of 45948
Processed 8200 out of 45948
Processed 8300 out of 45948
Processed 8400 out of 45948
Processed 8500 out of 45948
Processed 8600 out of 45948
Processed 8700 out of 45948
Processed 8800 out of 45948
Processed 8900 out of 45948
Processed 9000 out of 45948
Processed 9100 out of 45948
Processed 9200 out of 45948
Processed 9300 out of 45948
Processed 9400 out of 45948
Processed 9500 out of 45948
Processed 9600 out of 45948
Processed 9700 out of 45948
Processed 9800 out of 45948
Processed 9900 out of 45948
Processed 10000 out of 45948
Processed 10100 out of 45948
Processed 10200 out of 45948
Processed 10300 out of 45948
Processed 10400 out of 45948
Processed 10500 out of 45948
Processed 10600 out of 45948
Processed 10700 out of 45948
Processed 10800 out of 45948
Processed 10900 out of 45948
Processed 11000 out of 45948
Processed 11100 out of 45948
Processed 11200 out of 45948
Processed 11300 out of 45948
Processed 11400 out of 45948
Processed 11500 out of 45948
Processed 11600 out of 45948
Processed 11700 out of 45948
Processed 11800 out of 45948
Processed 11900 out of 45948
Processed 12000 out of 45948
Processed 12100 out of 45948
Processed 12200 out of 45948
Processed 12300 out of 45948
Processed 12400 out of 45948
Processed 12500 out of 45948
Processed 12600 out of 45948
Processed 12700 out of 45948
Processed 12800 out of 45948
Processed 12900 out of 45948
Processed 13000 out of 45948
Processed 13100 out of 45948
Processed 13200 out of 45948
Processed 13300 out of 45948
Processed 13400 out of 45948
Processed 13500 out of 45948
Processed 13600 out of 45948
Processed 13700 out of 45948
Processed 13800 out of 45948
Processed 13900 out of 45948
Processed 14000 out of 45948
Processed 14100 out of 45948
Processed 14200 out of 45948
Processed 14300 out of 45948
Processed 14400 out of 45948
Processed 14500 out of 45948
Processed 14600 out of 45948
Processed 14700 out of 45948
Processed 14800 out of 45948
Processed 14900 out of 45948
Processed 15000 out of 45948
Processed 15100 out of 45948
Processed 15200 out of 45948
Processed 15300 out of 45948
Processed 15400 out of 45948
Processed 15500 out of 45948
Processed 15600 out of 45948
Processed 15700 out of 45948
Processed 15800 out of 45948
Processed 15900 out of 45948
Processed 16000 out of 45948
Processed 16100 out of 45948
Processed 16200 out of 45948
Processed 16300 out of 45948
Processed 16400 out of 45948
Processed 16500 out of 45948
Processed 16600 out of 45948
Processed 16700 out of 45948
Processed 16800 out of 45948
Processed 16900 out of 45948
Processed 17000 out of 45948
Processed 17100 out of 45948
Processed 17200 out of 45948
Processed 17300 out of 45948
Processed 17400 out of 45948
Processed 17500 out of 45948
Processed 17600 out of 45948
Processed 17700 out of 45948
Processed 17800 out of 45948
Processed 17900 out of 45948
Processed 18000 out of 45948
Processed 18100 out of 45948
Processed 18200 out of 45948
Processed 18300 out of 45948
Processed 18400 out of 45948
Processed 18500 out of 45948
Processed 18600 out of 45948
Processed 18700 out of 45948
Processed 18800 out of 45948
Processed 18900 out of 45948
Processed 19000 out of 45948
Processed 19100 out of 45948
Processed 19200 out of 45948
Processed 19300 out of 45948
Processed 19400 out of 45948
Processed 19500 out of 45948
Processed 19600 out of 45948
Processed 19700 out of 45948
Processed 19800 out of 45948
Processed 19900 out of 45948
Processed 20000 out of 45948
Processed 20100 out of 45948
Processed 20200 out of 45948
Processed 20300 out of 45948
Processed 20400 out of 45948
Processed 20500 out of 45948
Processed 20600 out of 45948
Processed 20700 out of 45948
Processed 20800 out of 45948
Processed 20900 out of 45948
Processed 21000 out of 45948
Processed 21100 out of 45948
Processed 21200 out of 45948
Processed 21300 out of 45948
Processed 21400 out of 45948
Processed 21500 out of 45948
Processed 21600 out of 45948
Processed 21700 out of 45948
Processed 21800 out of 45948
Processed 21900 out of 45948
Processed 22000 out of 45948
Processed 22100 out of 45948
Processed 22200 out of 45948
Processed 22300 out of 45948
Processed 22400 out of 45948
Processed 22500 out of 45948
Processed 22600 out of 45948
Processed 22700 out of 45948
Processed 22800 out of 45948
Processed 22900 out of 45948
Processed 23000 out of 45948
Processed 23100 out of 45948
Processed 23200 out of 45948
Processed 23300 out of 45948
Processed 23400 out of 45948
Processed 23500 out of 45948
Processed 23600 out of 45948
Processed 23700 out of 45948
Processed 23800 out of 45948
Processed 23900 out of 45948
Processed 24000 out of 45948
Processed 24100 out of 45948
Processed 24200 out of 45948
Processed 24300 out of 45948
Processed 24400 out of 45948
Processed 24500 out of 45948
Processed 24600 out of 45948
Processed 24700 out of 45948
Processed 24800 out of 45948
Processed 24900 out of 45948
Processed 25000 out of 45948
Processed 25100 out of 45948
Processed 25200 out of 45948
Processed 25300 out of 45948
Processed 25400 out of 45948
Processed 25500 out of 45948
Processed 25600 out of 45948
Processed 25700 out of 45948
Processed 25800 out of 45948
Processed 25900 out of 45948
Processed 26000 out of 45948
Processed 26100 out of 45948
Processed 26200 out of 45948
Processed 26300 out of 45948
Processed 26400 out of 45948
Processed 26500 out of 45948
Processed 26600 out of 45948
Processed 26700 out of 45948
Processed 26800 out of 45948
Processed 26900 out of 45948
Processed 27000 out of 45948
Processed 27100 out of 45948
Processed 27200 out of 45948
Processed 27300 out of 45948
Processed 27400 out of 45948
Processed 27500 out of 45948
Processed 27600 out of 45948
Processed 27700 out of 45948
Processed 27800 out of 45948
Processed 27900 out of 45948
Processed 28000 out of 45948
Processed 28100 out of 45948
Processed 28200 out of 45948
Processed 28300 out of 45948
Processed 28400 out of 45948
Processed 28500 out of 45948
Processed 28600 out of 45948
Processed 28700 out of 45948
Processed 28800 out of 45948
Processed 28900 out of 45948
Processed 29000 out of 45948
Processed 29100 out of 45948
Processed 29200 out of 45948
Processed 29300 out of 45948
Processed 29400 out of 45948
Processed 29500 out of 45948
Processed 29600 out of 45948
Processed 29700 out of 45948
Processed 29800 out of 45948
Processed 29900 out of 45948
Processed 30000 out of 45948
Processed 30100 out of 45948
Processed 30200 out of 45948
Processed 30300 out of 45948
Processed 30400 out of 45948
Processed 30500 out of 45948
Processed 30600 out of 45948
Processed 30700 out of 45948
Processed 30800 out of 45948
Processed 30900 out of 45948
Processed 31000 out of 45948
Processed 31100 out of 45948
Processed 31200 out of 45948
Processed 31300 out of 45948
Processed 31400 out of 45948
Processed 31500 out of 45948
Processed 31600 out of 45948
Processed 31700 out of 45948
Processed 31800 out of 45948
Processed 31900 out of 45948
Processed 32000 out of 45948
Processed 32100 out of 45948
Processed 32200 out of 45948
Processed 32300 out of 45948
Processed 32400 out of 45948
Processed 32500 out of 45948
Processed 32600 out of 45948
Processed 32700 out of 45948
Processed 32800 out of 45948
Processed 32900 out of 45948
Processed 33000 out of 45948
Processed 33100 out of 45948
Processed 33200 out of 45948
Processed 33300 out of 45948
Processed 33400 out of 45948
Processed 33500 out of 45948
Processed 33600 out of 45948
Processed 33700 out of 45948
Processed 33800 out of 45948
Processed 33900 out of 45948
Processed 34000 out of 45948
Processed 34100 out of 45948
Processed 34200 out of 45948
Processed 34300 out of 45948
Processed 34400 out of 45948
Processed 34500 out of 45948
Processed 34600 out of 45948
Processed 34700 out of 45948
Processed 34800 out of 45948
Processed 34900 out of 45948
Processed 35000 out of 45948
Processed 35100 out of 45948
Processed 35200 out of 45948
Processed 35300 out of 45948
Processed 35400 out of 45948
Processed 35500 out of 45948
Processed 35600 out of 45948
Processed 35700 out of 45948
Processed 35800 out of 45948
Processed 35900 out of 45948
Processed 36000 out of 45948
Processed 36100 out of 45948
Processed 36200 out of 45948
Processed 36300 out of 45948
Processed 36400 out of 45948
Processed 36500 out of 45948
Processed 36600 out of 45948
Processed 36700 out of 45948
Processed 36800 out of 45948
Processed 36900 out of 45948
Processed 37000 out of 45948
Processed 37100 out of 45948
Processed 37200 out of 45948
Processed 37300 out of 45948
Processed 37400 out of 45948
Processed 37500 out of 45948
Processed 37600 out of 45948
Processed 37700 out of 45948
Processed 37800 out of 45948
Processed 37900 out of 45948
Processed 38000 out of 45948
Processed 38100 out of 45948
Processed 38200 out of 45948
Processed 38300 out of 45948
Processed 38400 out of 45948
Processed 38500 out of 45948
Processed 38600 out of 45948
Processed 38700 out of 45948
Processed 38800 out of 45948
Processed 38900 out of 45948
Processed 39000 out of 45948
Processed 39100 out of 45948
Processed 39200 out of 45948
Processed 39300 out of 45948
Processed 39400 out of 45948
Processed 39500 out of 45948
Processed 39600 out of 45948
Processed 39700 out of 45948
Processed 39800 out of 45948
Processed 39900 out of 45948
Processed 40000 out of 45948
Processed 40100 out of 45948
Processed 40200 out of 45948
Processed 40300 out of 45948
Processed 40400 out of 45948
Processed 40500 out of 45948
Processed 40600 out of 45948
Processed 40700 out of 45948
Processed 40800 out of 45948
Processed 40900 out of 45948
Processed 41000 out of 45948
Processed 41100 out of 45948
Processed 41200 out of 45948
Processed 41300 out of 45948
Processed 41400 out of 45948
Processed 41500 out of 45948
Processed 41600 out of 45948
Processed 41700 out of 45948
Processed 41800 out of 45948
Processed 41900 out of 45948
Processed 42000 out of 45948
Processed 42100 out of 45948
Processed 42200 out of 45948
Processed 42300 out of 45948
Processed 42400 out of 45948
Processed 42500 out of 45948
Processed 42600 out of 45948
Processed 42700 out of 45948
Processed 42800 out of 45948
Processed 42900 out of 45948
Processed 43000 out of 45948
Processed 43100 out of 45948
Processed 43200 out of 45948
Processed 43300 out of 45948
Processed 43400 out of 45948
Processed 43500 out of 45948
Processed 43600 out of 45948
Processed 43700 out of 45948
Processed 43800 out of 45948
Processed 43900 out of 45948
Processed 44000 out of 45948
Processed 44100 out of 45948
Processed 44200 out of 45948
Processed 44300 out of 45948
Processed 44400 out of 45948
Processed 44500 out of 45948
Processed 44600 out of 45948
Processed 44700 out of 45948
Processed 44800 out of 45948
Processed 44900 out of 45948
Processed 45000 out of 45948
Processed 45100 out of 45948
Processed 45200 out of 45948
Processed 45300 out of 45948
Processed 45400 out of 45948
Processed 45500 out of 45948
Processed 45600 out of 45948
Processed 45700 out of 45948
Processed 45800 out of 45948
Processed 45900 out of 45948
Processed 46000 out of 45948

In [62]:
len(embedding_reviews)

45948

In [63]:
def get_embedding(text, model="text-embedding-3-small"):
    response = openai.embeddings.create(
        input=[text],
        model=model,
    )
    return response.data[0].embedding

In [64]:
def retrieve_prefiltered_reviews_data(query, parent_asins, k=5):

    query_embedding = get_embedding(query)

    results = qdrant_client.query_points(
        collection_name="Amazon-items-collection-01-reviews",
        prefetch=[
            Prefetch(
                query=query_embedding,
                filter=Filter(
                    must=[
                        FieldCondition(
                            key="parent_asin",
                            match=MatchAny(
                                any=parent_asins
                            )
                        )
                    ]
                ),
                limit=20
            )
        ],
        query=FusionQuery(fusion="rrf"),
        limit=k
    )

    return results

In [67]:
reviews = retrieve_prefiltered_reviews_data("bad quality", ["B09WCFC5D9"])

In [69]:
reviews.points

[ScoredPoint(id=16121, version=363, score=0.5, payload={'text': 'Not good. I can’t find the return item area. Not good sound.', 'parent_asin': 'B09WCFC5D9'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=25017, version=452, score=0.33333334, payload={'text': 'Do not buy thes unless you only want them for phone calls. There is zero music quality They claim These buds to have deep bass, are enhanced, however there is zero bass reproduction. The voices singing or phone call sound horrible. The Bluetooth connect when you aren’t using them. The lid is not easy to open. The only reason I didn’t give one star is because people on the other end of the phone call can hear me great. Yet they do not on this end. But it will work. Music or app are always dropping or stopping. I don’t know why. Do not buy these earbuds.', 'parent_asin': 'B09WCFC5D9'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=7950, version=281, score=0.25, payload={'text': 'Looks pretty cool but pretty average sound Bass is not very strong, very treble biased<br />it has taken my earring off twice now<br /> not really its fault but the magnet it uses to attach itself to the charger is good at that<br />You get a mini RGB light show when you open the case.<br /><br />Update: microphone sucks, will return', 'parent_asin': 'B09WCFC5D9'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=40427, version=606, score=0.2, payload={'text': 'Nice for the price Good sound quality, easy to use, not the most comfortable, and the flashing lights I find can be a bit annoying at times, but for the price they are excellent!', 'parent_asin': 'B09WCFC5D9'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=42582, version=627, score=0.16666667, payload={'text': "Good sound but uncomfortable fit I couldn't use them because they hurt my ears. Over than that they", 'parent_asin': 'B09WCFC5D9'}, vector=None, shard_key=None, order_value=None)]